# Generated by Django 3.1.6 on 2021-02-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djuser',
            name='level',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
